# Generated by Django 5.1.3 on 2025-02-06 08:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Votre nom de famille', max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(help_text='Vos prénoms', max_length=150, verbose_name='Prénoms')),
                ('biography', models.TextField(help_text='Une brève description de vous', verbose_name='Biographie')),
                ('profil_pictures', models.ImageField(blank=True, help_text='Téléchargez une photo de profil', null=True, upload_to='portfolio/', verbose_name='Photo de profil')),
                ('resume_link', models.URLField(blank=True, help_text='URL vers votre CV en ligne', null=True, verbose_name='Lien vers le CV')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('url_blog', models.URLField(blank=True, null=True)),
                ('author_articles', models.CharField(max_length=200, null=True, verbose_name='Auteur')),
                ('date_published', models.DateTimeField(null=True, verbose_name='Date de publication')),
                ('categorie', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet du message')),
                ('message', models.TextField(verbose_name='Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé à')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=200, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('skills_used', models.CharField(max_length=500, verbose_name='Compétences utilisées')),
                ('image_project', models.ImageField(blank=True, null=True, upload_to='portfolio_projects/', verbose_name='Image du projet')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='Lien GitHub')),
                ('url_project', models.URLField(blank=True, null=True, verbose_name='URL du projet')),
                ('date_project_update', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise à jour')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('DEVOPS', 'DevOps'), ('DATABASE', 'Base de données'), ('OTHER', 'Autre')], max_length=200, verbose_name='Catégorie')),
                ('skills_name', models.CharField(max_length=100, verbose_name='Nom de la compétence')),
                ('level', models.IntegerField(default=50, help_text='Niveau de maîtrise en pourcentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Niveau de maîtrise')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_requested', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='port_data.contact')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='port_data.service')),
            ],
        ),
    ]
