# Generated by Django 5.1.3 on 2024-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='name')),
                ('prenoms', models.CharField(max_length=150)),
                ('biography', models.TextField()),
                ('profil_pictures', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('resume_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('image_blog', models.ImageField(blank=True, null=True, upload_to='portfolio_articles/')),
                ('url_blog', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('skills_used', models.CharField(max_length=500)),
                ('image_project', models.ImageField(blank=True, null=True, upload_to='portfolio_projects/')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('url_project', models.URLField(blank=True, null=True)),
                ('date_project_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('skills_name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=50)),
            ],
        ),
    ]
