# Generated by Django 5.1.3 on 2025-02-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_article',
            field=models.CharField(max_length=200, null=True, verbose_name='Auteur'),
        ),
    ]
