# Generated by Django 5.1.3 on 2025-02-09 23:34

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=255, default='', verbose_name='Sujet du message'),
)

    ]
