# Generated by Django 5.1.3 on 2024-11-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
