# Generated by Django 5.1.3 on 2025-02-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skills_used',
        ),
        migrations.AddField(
            model_name='project',
            name='skills_used',
            field=models.ManyToManyField(related_name='projects', to='port_data.skill', verbose_name='Compétences utilisées'),
        ),
    ]
