# Generated by Django 5.1.3 on 2025-03-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_article',
            field=models.URLField(blank=True, null=True),
        ),
    ]
