# Generated by Django 5.1.3 on 2025-02-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0002_article_author_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('DATA', 'Data Science'), ('Python', 'Django-Flasks'), ('Mlops', 'Mlop Data Infra'), ('DATABASE', 'SQL, MySQL, PostgreSQL'), ('DEEP lEARNING', 'Tensorflow, Keras, Pytorch'), ('NLP:Natural Language Processing', 'NLTK, Spacy, Gensim, word2vec'), ('MACHINE lEARNING', 'Scikit-learn, XGBoost, LightGBM')], default='Category', max_length=200, verbose_name='Catégorie'),
        ),
    ]
