# Generated by Django 5.1.3 on 2024-11-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0002_alter_about_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject_message', models.TextField()),
                ('content_message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=50)),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
