# Generated by Django 5.1.3 on 2025-02-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0002_auto_20250209_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Sujet du message'),
        ),
    ]
