# Generated by Django 5.1.3 on 2025-04-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0002_alter_article_image_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='email_client',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='name_client',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='budget_estimated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Budget estimé'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='delai_livraison',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Delai de livraison'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='details_project',
            field=models.TextField(blank=True, null=True, verbose_name='Détails du projet'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='entreprise',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='téléphone',
            field=models.CharField(default='0000000000', max_length=100, verbose_name='Téléphone du client'),
        ),
    ]
