# Generated by Django 5.1.3 on 2025-02-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0002_remove_project_skills_used_project_skills_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_project',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image du projet'),
        ),
    ]
