# Generated by Django 5.1.3 on 2025-04-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0003_rename_email_client_servicerequest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_article',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]

