# Generated by Django 5.1.3 on 2025-02-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0003_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='message',
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email_client',
            field=models.EmailField(default='name_client@gmail.com', max_length=254, verbose_name='Adresse email du client'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='name_client',
            field=models.CharField(default='nom@CharField', max_length=100, verbose_name='Nom du client'),
        ),
    ]
