# Generated by Django 5.1.3 on 2025-02-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0003_alter_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=100, default='', verbose_name='Message'),
)

    ]
