# Generated by Django 5.1.3 on 2025-02-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0004_auto_20250209_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
