# Generated by Django 5.1.3 on 2024-12-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0005_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='name')),
                ('prenom', models.CharField(max_length=500, verbose_name='surname')),
                ('email', models.EmailField(blank=True, default='_C@EmailField', max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
