# Generated by Django 5.1.3 on 2024-12-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0006_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author_articles',
            field=models.CharField(max_length=200, null=True, verbose_name='auteur'),
        ),
        migrations.AddField(
            model_name='articles',
            name='categorie',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de publication'),
        ),
    ]
