# Generated by Django 5.1.3 on 2024-12-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0009_contact_is_read_newsletter_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
