# Generated by Django 5.1.3 on 2024-12-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0010_alter_newsletter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
