# Generated by Django 5.1.3 on 2024-12-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0011_alter_article_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='client_email',
            new_name='email_client',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='client_name',
            new_name='name_client',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_blog',
        ),
    ]
