# Generated by Django 5.1.4 on 2025-01-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0013_alter_newsletter_is_active_alter_newsletter_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
