# Generated by Django 5.1.3 on 2025-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_data', '0014_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_articles',
            field=models.CharField(max_length=200, null=True, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(null=True, verbose_name='Date de publication'),
        ),
    ]
