databases:
  - name: portfoliodb
    plan: free
    databaseName: portfolio
    user: portfolio

services:
  - type: web
    plan: free
    name: portfolio
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn Data_Portfolio.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfoliodb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
