-- Active: 1735120816342@@127.0.0.1@5432
"""
Django settings for Data_Portfolio project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

#host: db.lmvicsqzsaxyftqeymxs.supabase.co

#port:5432

#database:postgres

#user:postgres






from pathlib import Path
import os
import urllib.parse
from dotenv import load_dotenv
import dj_database_url
load_dotenv()
import logging

logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s %(levelname)s %(message)s',
)

#import environ



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# settings.py

ADMIN_EMAIL=os.getenv("ADMIN_EMAIL")
SECRET_KEY=os.getenv("SECRET_KEY")

LOGIN_URL=os.getenv("LOGIN_URL")
LOGIN_REDIRECT_URL=os.getenv("LOGIN_REDIRECT_URL")
DEBUG=os.getenv("DEBUG")
EMAIL_LIST=os.getenv("EMAIL_LIST")

USER_ID=os.getenv("USER_ID")
#ALLOWED_HOSTS=.onrender.com

# BASE DE DONNÉES POSTGRESQL
DATABASE_URL=os.getenv("DATABASE_URL")

# configuration du serveur smtp pour mailtrip using in production
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS") # Sécurisation de la connexion
#EMAIL_USE_SSL = False  # Sécurisation de la connexion
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
EMAIL_ADMIN = os.getenv("EMAIL_ADMIN")

## apis of mailtrap
MAILTRAP_API_TOKEN = os.getenv('MAILTRAP_API_TOKEN')



#EMAIL_HOST = os.getenv("EMAIL_HOST")
#EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
#EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
#EMAIL_PORT = os.getenv("EMAIL_PORT")
#EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
#EMAIL_USE_SSL= os.getenv("EMAIL_USE_SSL")
#DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
#EMAIL_ADMIN = os.getenv('EMAIL_ADMIN')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


#LOGIN_URL, LOGIN_REDIRECT_URL = os.getenv("LOGIN_URL"), os.getenv("LOGIN_REDIRECT_URL")

#EMAIL_LIST = os.getenv("EMAIL_LIST")
# SECURITY WARNING: don't run with debug turned on in production!
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_HOST = "smtp-relay.brevo.com"  # Serveur SMTP de Brevo
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#EMAIL_HOST_USER = "855728001@smtp-brevo.com"  # Remplace par ton email Brevo
#EMAIL_HOST_PASSWORD = "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"  # Remplace par le mot de passe de l'application
#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
#EMAIL_ADMIN = "donaerickoulodji@gmail.com"  # Ton email d'admin pour recevoir les messages


ALLOWED_HOSTS = ["127.0.0.1", "localhost", "192.168.65.42", ".onrender.com"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "port_data",
    "Authentification",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Data_Portfolio.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Data_Portfolio.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


#DATABASES = {
   # 'default': dj_database_url.config(
  #      default=DATABASE_URL
 #   )
#}

DATABASES = {
    "default":
        {
            "ENGINE":"django.db.backends.postgresql",
            "NAME":'gptdb',
            'USER':"erick",
            'PASSWORD':"Endrick@#",
            'HOST':"127.0.0.1",
           'PORT':'5432'
        }
}
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "Authentification.validators.ContainsLetterValidator",
    },
    # {
    #   'NAME': 'Authentification.validators.ContainsNumberValidator',
    # }
]

# mises en caches
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "cache_data",
    }
}
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
if DEBUG:
    STATIC_FILES = [BASE_DIR / "static"]
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR.joinpath("media/")

# Authentification user

AUTH_MODEL_USER = "Authentification.User"