"""
Django settings for Data_Portfolio project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import urllib.parse
from dotenv import load_dotenv
import dj_database_url
load_dotenv()
import logging

logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s %(levelname)s %(message)s',
)

#import environ



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# settings.py

ADMIN_EMAIL='koulodjieric16@gmail.com'
SECRET_KEY='django-insecure-6)$@l81a-k7w3#z^dnhxj79+g$mv%(lr62ua5+b71i@j(9apt7'

LOGIN_URL='login'
LOGIN_REDIRECT_URL='home'
DEBUG=True
EMAIL_LIST=['donaerickoulodji@gmail.com', "koulodjieric16@gmail.com"]

USER_ID="koulodjiric"
#ALLOWED_HOSTS=.onrender.com

# BASE DE DONNÉES POSTGRESQL
DATABASE_URL="postgresql://eric:VhhDWm7XIhn1mhePJT4lYbMwqjUcBmgY@dpg-cu2fhbqj1k6c73ckj120-a.oregon-postgres.render.com/portfoliodb_h8y3"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_HOST_USER = 'c5e9d61921d033'
EMAIL_HOST_PASSWORD = '********86bd'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # Sécurisation de la connexion
#EMAIL_USE_SSL = False  # Sécurisation de la connexion
DEFAULT_FROM_EMAIL = "koulodjieric16@gmail.com"
EMAIL_ADMIN = "donaerickoulodji@gmail.com"


MAILTRAP_API_TOKEN = "8d73f9afe66d1ae3b08a823808729e92"



#EMAIL_HOST = os.getenv("EMAIL_HOST")
#EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
#EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
#EMAIL_PORT = os.getenv("EMAIL_PORT")
#EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
#EMAIL_USE_SSL= os.getenv("EMAIL_USE_SSL")
#DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
#EMAIL_ADMIN = os.getenv('EMAIL_ADMIN')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = os.getenv("SECRET_KEY")

#ADMIN_EMAIL = os.getenv("ADMIN_EMAIL")

#DEBUG = os.getenv("DEBUG")

#LOGIN_URL, LOGIN_REDIRECT_URL = os.getenv("LOGIN_URL"), os.getenv("LOGIN_REDIRECT_URL")

#EMAIL_LIST = os.getenv("EMAIL_LIST")
# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ["127.0.0.1", "localhost", "192.168.65.42", ".onrender.com"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "port_data",
    "Authentification",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Data_Portfolio.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Data_Portfolio.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600
    )
}
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "Authentification.validators.ContainsLetterValidator",
    },
    # {
    #   'NAME': 'Authentification.validators.ContainsNumberValidator',
    # }
]

# mises en caches
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "cache_data",
    }
}
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
if DEBUG:
    STATIC_FILES = [BASE_DIR / "static"]
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR.joinpath("media/")

# Authentification user

AUTH_MODEL_USER = "Authentification.User"


#env = environ.Env()
#environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

#password = "Endrick@#"
#encoded_password = urllib.parse.quote(password)
#print(encoded_password)
